version: '3'

tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [staticcheck]
    cmds:
      - go test -cover ./...
  test-v:
    deps: [staticcheck]
    cmds:
      - go test -cover -race -v ./...
  fmt:
    cmds:
      - go fmt ./...
  vet:
    deps: [fmt]
    cmds:
      - go vet ./...
  staticcheck:
    deps: [vet]
    cmds:
      - staticcheck ./...
  run:
    deps: [staticcheck]
    cmds:
      - go run cmd/prxmail/main.go
  build:
    deps: [staticcheck]
    cmds:
      - go build -ldflags "-X main.Revision={{.GIT_HASH}}" -o prxmail.exe cmd/prxmail/main.go
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    vars:
      GIT_HASH:
        sh: git rev-parse HEAD

